### ISSUE TITLE
Application Launch error after update

### ISSUE THREAD

**Issue by shaymongracia** [red-soft-ru/redexpert#5]
Hello everyone, Im getting an error when trying to open de RedExpert app. It happens after update the version, I tried re-installing java and also re-installing RedExpert but still getting same error 

java.lang.NullPointerException
	at org.executequery.GUIUtilities.setDockedTabViews(GUIUtilities.java:1412)
	at org.executequery.GUIUtilities.initPanels(GUIUtilities.java:222)
	at org.executequery.ApplicationLauncher.startup(ApplicationLauncher.java:171)
	at org.executequery.ExecuteQuery.<init>(ExecuteQuery.java:34)
	at org.executequery.ExecuteQuery.main(ExecuteQuery.java:63)

![2020-10-04 12_15_16-Error Message](https://user-images.githubusercontent.com/46830506/95022205-5ee78380-063b-11eb-8fea-89fd8f96f664.png)

**Comment by mikhan808** [comment]
Please archive and send us (rdb.support@red-soft.ru) the ".redexpert" directory located in the Home directory (for example, "C:\users\username"). Perhaps the problem is caused by wrong settings. You  can try to delete or rename this directory and run the program with the default settings. Please let us know about the result.

**Comment by shaymongracia** [comment]
Hi @mikhan808, that actually work. I just rename that folder and reopen the app and it just work.
Thanks for the support
